merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("bands/", views.band_list, name="band_list"),
    path("bands/<int:band_id>/", views.band_detail, name="band_detail"),
    path("bands/<int:band_id>/update/", views.band_update, name="band_update"),
    path("bands/<int:band_id>/delete/", views.band_delete, name="band_delete"),
    path("bands/add/", views.band_create, name="band_create"),
    path("listings/", views.listings, name="listing_list"),
    path("listings/<int:listing_id>/", views.listing_detail, name="listing_detail"),
    path("listings/add/", views.listing_create, name="listing_create"),
    path("listings/<int:listing_id>/update/", views.listing_update, name="listing_update"),
    path("listings/<int:listing_id>/delete/", views.listing_delete, name="listing_delete"),
    path("about-us", views.about, name="about"),
    path("contact-us", views.contact, name="contact"),
    path("email-sent", views.email_sent, name="email_sent"),
]

handler404 = views.page_not_found

merchex/listings/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator


class Band(models.Model):
    class Genre(models.TextChoices):
        HIP_HOP = "HH"
        SYNTH_POP = "SP"
        ALTERNATIVE_ROCK = "AR"

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(max_length=50)
    biography = models.fields.CharField(max_length=100)
    year_formed = models.fields.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2021)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    # like_new = models.fields.BooleanField(default=False)

    def __str__(self):
        return self.name


class Listing(models.Model):
    class Type(models.TextChoices):
        RECORDS = "Records"
        CLOTHING = "Clothing"
        POSTERS = "Posters"
        MISCELLANEOUS = "Miscellaneous"

    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    sold = models.BooleanField(default=False)
    year = models.IntegerField(
        validators=[MinValueValidator(1900), MaxValueValidator(2021)], blank=True
    )
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.title

merchex/listings/forms.py
from django import forms

from .models import Band, Listing


class ContactsUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)


class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        # fields = "__all__"
        exclude = ["active", "official_homepage"]


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = "__all__"

merchex/listings/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.core.mail import send_mail


from .forms import BandForm, ContactsUsForm, ListingForm

from .models import Band, Listing


def page_not_found(request, exception):
    print(exception)
    return render(request, "404.html")


def email_sent(request):
    print(f"client ip = {get_client_ip(request)}")
    return render(request, "listings/email_sent.html")


def band_list(request):
    bands = Band.objects.all()
    print(f"client ip = {get_client_ip(request)}")
    return render(request, "listings/band_list.html", {"bands": bands})


def band_detail(request, band_id):
    band = get_object_or_404(Band, pk=band_id)
    return render(request, "listings/band_detail.html", {"band": band})


def band_update(request: HttpRequest, band_id: int):
    band = get_object_or_404(Band, pk=band_id)
    if request.method == "POST":
        form = BandForm(request.POST, instance=band)
        if form.is_valid():
            form.save()
            return redirect("band_detail", band.id)
    else:
        form = BandForm(instance=band)
    return render(request, "listings/band_update.html", {"form": form})


def band_create(request: HttpRequest):
    if request.method == "POST":
        form = BandForm(request.POST)
        if form.is_valid():
            band = form.save()
            return redirect("band_detail", band.id)
    else:
        form = BandForm()
    return render(request, "listings/band_create.html", {"form": form})


def band_delete(request, band_id):
    band = Band.objects.get(id=band_id)
    if request.method == "POST":
        band.delete()
        return redirect("band_list")
    return render(request, "listings/band_delete.html", {"band": band})


def listings(request):
    listings = Listing.objects.all()
    if len(listings) == 0:
        titles = [
            "Affiche ORIGINALE de la tournée de De La Soul - Fillmore Auditorium San Francisco novembre 2001",
            "T-shirt du concert de Cut Copy, tournée Free Your Mind, 2013",
            "Foo Fighters - l’affiche promo du single Big Me, fin des années 90",
            "Beethoven - Sonate au clair de lune - manuscrit original EXTRÊMEMENT RARE",
        ]
        for title in titles:
            Listing.objects.create(title=title)
        listings = Listing.objects.all()
    print(f"client ip = {get_client_ip(request)}")
    return render(request, "listings/listings.html", {"listings": listings})


def listing_detail(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    return render(request, "listings/listing_detail.html", {"listing": listing})


def listing_update(request: HttpRequest, listing_id: int):
    listing = get_object_or_404(Listing, pk=listing_id)
    if request.method == "POST":
        form = ListingForm(request.POST, instance=listing)
        if form.is_valid():
            form.save()
            return redirect("listing_detail", listing.id)
    else:
        form = ListingForm(instance=listing)
    return render(request, "listings/listing_update.html", {"form": form})


def listing_create(request: HttpRequest):
    if request.method == "POST":
        form = ListingForm(request.POST)
        if form.is_valid():
            listing = form.save()
            return redirect("listing_detail", listing.id)
    else:
        form = ListingForm()
    return render(request, "listings/listing_create.html", {"form": form})


def listing_delete(request, listing_id: str):
    listing = Listing.objects.get(id=listing_id)
    if request.method == "POST":
        listing.delete()
        return redirect("listing_list")
    return render(request, "listings/listing_delete.html", {"listing": listing})


def contact(request):
    print(f"client ip = {get_client_ip(request)}")
    print("La méthode de requête est : ", request.method)
    print("Les données POST sont : ", request.POST)
    if request.method == "POST":
        form = ContactsUsForm(request.POST)
        if form.is_valid():
            send_mail(
                subject=f"message from {form.cleaned_data['name'] or 'anonyme'} via Merchex Contact Us form",
                message=form.cleaned_data["message"],
                from_email=form.cleaned_data["email"],
                recipient_list=["admin@merchex.xyz"],
            )
            return redirect("email_sent")
    else:
        form = ContactsUsForm()
    return render(request, "listings/contact.html", {"form": form})


def about(request):
    print(f"client ip = {get_client_ip(request)}")
    return render(request, "about.html")


def get_client_ip(request):
    x_forwarded_for = request.META.get("HTTP_X_FORWARDED_FOR")
    if x_forwarded_for:
        ip = x_forwarded_for.split(",")[0]
    else:
        ip = request.META.get("REMOTE_ADDR")
    return ip

merchex/listings/templates/about.html
{% extends 'base.html' %}

{% block content %}

        <h1>A propos</h1>
        <p>Nous adorons merch !</p>

{% endblock %}

merchex/listings/templates/base.html
{% load static %}

<html>
    <head>
        <title>Merchex</title>
        <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />
    </head>
    <body>
        <p>
            <a href="{% url 'listing_list' %}">listings</a>
            <a href="{% url 'band_list' %}">bands</a>
            <a href="{% url 'contact' %}">Contact</a>
            <a href="{% url 'about' %}">A propos</a>
        </p>
        {% block content %}{% endblock %}
    </body>
</html>

merchex/listings/templates/listings/band_create.html
{% extends 'base.html' %}

{% block content %}

<h1>Création de groupe :</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Envoyer" />
</form>
{% endblock %}

merchex/listings/templates/listings/band_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Suppression du groupe :</h1>
<p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Supprimer">
</form>

<a href="{% url 'band_list' %}">Retour à la liste des groupes</a>
{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'base.html' %}

{% block content %}

<h1>Groupe : {{ band.name }}</h1>
<ul>
    <li>Genre : {{band.get_genre_display }}</li>
    <li>Année de formation : {{band.year_formed}}</li>
    <li>Actif : {{band.active | yesno}}</li>
    {% if band.official_homepage %}
    <li><a href="{{ band.official_homepage }}">{{ band.official_homepage }}</a></li>
    {% endif %}
</ul>
<p>{{ band.biography }}</p>
<a href="{% url 'band_update' band.id %}">[Modifier]</a><br />
<a href="{% url 'band_delete' band.id %}">[Supprimer]</a><br />
<a href="{% url 'band_list' %}">Retour à la liste des groupes</a>
{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'base.html' %}

{% block content %}

<h1>Groupes</h1>
<ul>
    {% for band in bands %}
         <li>
            <a href="{% url 'band_detail' band.id %}">{{ band.name }}</a>
            <a href="{% url 'band_update' band.id %}">[Modifier]</a>
            <a href="{% url 'band_delete' band.id %}">[Supprimer]</a>
        </li>
    {% endfor %}
</ul>
<a href="{% url 'band_create' %}">Créer un nvo groupe</a>
{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends 'base.html' %}

{% block content %}

<h1>Mise à jour du groupe :</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Envoyer">
</form>
<a href="{% url 'band_list' %}">Retour à la liste des groupes</a>
{% endblock %}

merchex/listings/templates/listings/contact.html
{% extends 'base.html' %}

{% block content %}

<h1>Contact</h1>
<p>Laissez nous un message !</p>

<form action="" method="post" novalidate>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Envoyer" />
</form>

{% endblock %}

merchex/listings/templates/listings/email_sent.html
{% extends 'base.html' %}

{% block content %}

<h1>Email envoyé</h1>
<p>Merci pour cette prise de contact, nous reviendrons vers vous au plus tôt</p>

{% endblock %}

merchex/listings/templates/listings/listing_create.html
{% extends 'base.html' %}

{% block content %}

<h1>Creation de listing :<h1>
<form action="" method="post">
{% csrf_token %}
{{form.as_p}}
<input type="submit" value="Envoyer" />
</form>
{% endblock %}

merchex/listings/templates/listings/listing_delete.html
{% extends 'base.html' %}

{% block content %}

<h1>Suppression du listing :</h1>
<p>Etes-vous sûr de vouloir supprimer le listing : {{ listing.title }} ?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Envoyer">
</form>
<a href="{% url 'listing_list' %}">Retour à la liste des listing</a>
{% endblock %}

merchex/listings/templates/listings/listing_detail.html
{% extends 'base.html' %}

{% block content %}

<h1>Listing : {{ listing.title }}</h1>
<ul>
    <li>Description : {{listing.description }}</li>
    <li>Année : {{listing.year}}</li>
    <li>Vendu : {{listing.sold | yesno}}</li>
    {% if listing.band %}
    <li><a href="{% url 'band_detail' listing.band.id %}">{{ listing.band }}</a></li>
    {% endif %}
</ul>

<a href="{% url 'listing_update' listing.id %}">[Modifier]</a><br />
<a href="{% url 'listing_delete' listing.id %}">[Supprimer]</a><br />
<a href="{% url 'listing_list' %}">Retour à la liste des listing</a>
{% endblock %}

merchex/listings/templates/listings/listing_update.html
{% extends 'base.html' %}

{% block content %}

<h1>Mise à jour du listing :</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Envoyer">
</form>
<a href="{% url 'listing_list' %}">Retour à la liste des listing</a>
{% endblock %}

merchex/listings/templates/listings/listings.html
{% extends 'base.html' %}

{% block content %}

<h1>Listings ({{ listing | length }})</h1>
<ul>
    {% for listing in listings %}
    <li>
        <a href="{% url 'listing_detail' listing.id %}">{{ listing.title | upper}}</a>
        <a href="{% url 'listing_update' listing.id %}">[Modifier]</a>
        <a href="{% url 'listing_delete' listing.id %}">[Supprimer]</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'listing_create' %}">Créer un nvo listing</a>
{% endblock %}